apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fargate-nginx-template
  title: Platform Engineering Demo Service
  description: Create a simple repository and pipeline
  tags:
    - recommended
    - eks
    - service
spec:
  owner: service@example.com
  type: service

  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoName
      properties:
        repoName:
          title: Repository Name
          type: string
          description: The name for this service
          
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          #initial_message: ${{ parameters.initial_message }}
          owner: ${{ parameters.owner }}
          #destination: ${{ parameters.repoUrl | parseRepoUrl }}
          repository_name: ${{ parameters.repoName }}
          # The AWS Proton environments to use for deploying the initial service instances
          aws_proton_environment_name: "env25"
          #aws_proton_prod_environment_name: "pe-demo-env"
          # The AWS account where the Proton service will be created
          aws_account_id: "672132031023"
          # The AWS region where the Proton service will be created
          aws_region: us-east-2

    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ["github.com"]
    #     description: This is ${{ parameters.component_id }}
    #     repoUrl: ${{ parameters.repoUrl }}
    #     repoVisibility: private
    #     defaultBranch: main
    #     sourcePath: ./repo-contents

    - id: create-proton-service
      name: Create AWS Proton Service
      action: aws:proton:create-service
      input:
        serviceName: ${{ parameters.component_id }}
        repositoryName: ${{ parameters.repoName }}
        #branchName: main
        serviceSpecPath: ./spec.yaml
        # Update the following fields to match the resources in your AWS account
        region: us-east-2
        templateName: pe-frontend-svc
        templateMajorVersion: '1'
        #repositoryConnectionArn: 'arn:aws:codestar-connections:us-east-1:672132031023:connection/ce4a1db0-1571-4e8f-bc63-2bb3bcc80e39'

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: "/catalog-info.yaml"

  # output:
  #   links:
  #     - title: Repository
  #       url: ${{ steps.publish.output.remoteUrl }}
  #     - title: Open in catalog
  #       icon: catalog
  #       entityRef: ${{ steps.register.output.entityRef }}
